improved docs for prepare-commit-msg

diff --git a/scripts/prepare-commit-msg b/scripts/prepare-commit-msg
--- a/scripts/prepare-commit-msg
+++ b/scripts/prepare-commit-msg
@@ -1,10 +1,16 @@
 #!/usr/bin/env bash
 
+# see README.md for more details
+# 
+# This hook expects to find environment variables
+# - "KNIME_ATLASSIAN_EMAIL"
+# - "KNIME_ATLASSIAN_API_TOKEN"
+# set in your path containing your Atlassian account email and API token
+# respectively. The latter can optionally be set using a secret storage tool
+
 set -uo pipefail
 
-# This hook expects to find environment variables "KNIME_ATLASSIAN_EMAIL" and "KNIME_ATLASSIAN_API_TOKEN" set in your
-# path containing your Attlassian account email and API token respectively. The latter can optionally be set using
-# a secret storage tool
+logPrefix="prepare-commit-msg git hook:"
 
 get_token_from_keychain() {
   local keyName="KNIME_ATLASSIAN_API_TOKEN"
@@ -21,13 +27,13 @@ get_token_from_keychain() {
       exitStatus=$?
       ;;
     *)
-      echo "KNIME_ATLASSIAN_API_TOKEN not set or unable to find it in keychain."
+      echo "$logPrefix KNIME_ATLASSIAN_API_TOKEN not set or unable to find it in keychain."
       exit 1
       ;;
   esac
 
   if [ "${exitStatus}" -ne 0 ]; then
-    echo "KNIME_ATLASSIAN_API_TOKEN not set or unable to find it in keychain."
+    echo "$logPrefix KNIME_ATLASSIAN_API_TOKEN not set or unable to find it in keychain."
     exit 1
   fi
 
@@ -35,17 +41,15 @@ get_token_from_keychain() {
 }
 
 check_env_variable() {
+  if [ -z "${KNIME_ATLASSIAN_EMAIL+x}" ]; then
+    echo "$logPrefix KNIME_ATLASSIAN_EMAIL not set."
+    exit 1
+  fi
+
   if [ -z "${KNIME_ATLASSIAN_API_TOKEN+x}" ]; then
     get_token_from_keychain
   fi
-
-  if [ -z "${KNIME_ATLASSIAN_EMAIL+x}" ]; then
-    echo "KNIME_ATLASSIAN_EMAIL not set."
-    exit 1
-  fi
 }
-
-check_env_variable
 
 # Read issue ID from branch name, read issue summary from the web,
 # and generate a commit message outline.
@@ -57,6 +61,8 @@ if [[ -z "$message" || "$message" = "message" ]]; then
   branch=$(git symbolic-ref --short HEAD)
 
   if [[ $branch =~ ^(.*/)?([A-Z]+-[0-9]+) ]]; then
+    check_env_variable
+
     issue_id=${BASH_REMATCH[2]}
     cachedir="/tmp/.gitjiratitle"
     cachefile="$cachedir/$issue_id"
